# Generated by Django 3.1.1 on 2023-05-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
    ]
