# Generated by Django 3.1.1 on 2023-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230516_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('pricing', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(related_name='hospitals', to='store.Service'),
        ),
    ]
