# Generated by Django 3.1.1 on 2023-05-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20230516_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentservice',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_payment_services', to='store.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='accepted_paymentservices',
            field=models.ManyToManyField(related_name='hospitals', to='store.PaymentService'),
        ),
    ]
