# Generated by Django 3.1.1 on 2023-05-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20230517_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hospital')),
            ],
        ),
    ]
