# Generated by Django 3.1.1 on 2023-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_serviceprovided'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='service_provided',
            field=models.ManyToManyField(related_name='hospitals', to='store.ServiceProvided'),
        ),
    ]
