# Generated by Django 3.1.1 on 2023-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_doctor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
