# Generated by Django 3.1.1 on 2023-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20230517_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('medical shuttle', 'Medical Shuttle')], max_length=20),
        ),
    ]
