# Generated by Django 3.1.1 on 2023-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20230517_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, default='we provide the best healthcare', max_length=500),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='hospital@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services_offered',
            field=models.CharField(default='Support Services, Diagnostic Services,Maternity Services,  Pediatric Services', max_length=50000),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(default='https://www.google.com/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('medical_shuttle', 'Medical Shuttle')], max_length=20),
        ),
    ]
