# Generated by Django 3.1.1 on 2023-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20230517_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pricing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
