# Generated by Django 3.1.1 on 2023-05-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20230517_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='pricing',
        ),
    ]
