# Generated by Django 3.1.1 on 2023-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_hospital_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='services_offered',
            field=models.CharField(default='Support Services, Diagnostic Services,Maternity Services,  Pediatric Services', max_length=50000, null=True),
        ),
    ]
