# Generated by Django 3.1.1 on 2023-05-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='home_available',
            field=models.BooleanField(default=False),
        ),
    ]
